# 网络请求设置
request:
  timeout: 10 # 超时设置
  ssl: false # ssl设置

# 要抓取的 issues 配置
issues:
  repo: xaoxuu/friends # 仓库持有者/仓库名
  labels: 
    - active # 必填，可以多选
  sort: # updated-desc # 排序，按最近更新，取消此项则按创建时间排序
